# Generated by Django 4.1.5 on 2023-05-10 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Combos',
            },
        ),
        migrations.CreateModel(
            name='DailyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Daily_orders',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stocks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_per_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measurement', models.CharField(max_length=20)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumpiasys.group')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='InventoryRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stocks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lumpiasys.product')),
            ],
            options={
                'db_table': 'Inventory_records',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combo_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lumpiasys.combo')),
                ('item_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lumpiasys.product')),
            ],
            options={
                'db_table': 'Components',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
    ]
