# Generated by Django 4.1.5 on 2023-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_level', models.IntegerField()),
                ('units_per_order', models.IntegerField()),
                ('group_name', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=20)),
            ],
        ),
    ]
