# Generated by Django 4.1.5 on 2023-04-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Combo',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_item', models.IntegerField()),
                ('units_of_measurement', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Components',
            },
        ),
        migrations.CreateModel(
            name='DailyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Daily_Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('target_level', models.IntegerField()),
                ('units_per_order', models.IntegerField()),
                ('group_name', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
