# Generated by Django 4.1.5 on 2023-04-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stocks',
        ),
    ]
