# Generated by Django 4.1.5 on 2023-02-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0002_alter_product_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remaining_inventory', models.IntegerField()),
                ('units_sold', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumpiasys.product')),
            ],
        ),
    ]
