# Generated by Django 4.1.5 on 2023-05-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('Can view remaining inventory', 'Admin'),)},
        ),
    ]
