# Generated by Django 4.1.5 on 2023-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0002_dailyorder_final_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='target_level',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
