# Generated by Django 4.1.5 on 2023-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0002_rename_stock_product_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.AlterModelTable(
            name='combo',
            table='Combos',
        ),
        migrations.AlterModelTable(
            name='dailyorder',
            table='Daily_Orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
