# Generated by Django 4.1.5 on 2023-04-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0003_groups_alter_combo_table_alter_dailyorder_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyorder',
            table='Daily_orders',
        ),
    ]
