# Generated by Django 4.1.5 on 2023-03-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0004_combo_components_dailyorder_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='combo',
            table='combo',
        ),
        migrations.AlterModelTable(
            name='components',
            table='components',
        ),
        migrations.AlterModelTable(
            name='dailyorder',
            table='daily_order',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
