# Generated by Django 4.1.5 on 2023-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0004_alter_dailyorder_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.AlterField(
            model_name='product',
            name='group_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
