# Generated by Django 4.0.4 on 2023-03-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0005_alter_combo_table_alter_components_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='combo',
            table='Combo',
        ),
        migrations.AlterModelTable(
            name='components',
            table='Components',
        ),
        migrations.AlterModelTable(
            name='dailyorder',
            table='Daily_order',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
