# Generated by Django 4.1.5 on 2023-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0005_rename_groups_group_alter_product_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_name',
            field=models.CharField(max_length=30),
        ),
    ]
