# Generated by Django 4.1.5 on 2023-03-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0006_alter_combo_table_alter_components_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyorder',
            old_name='orders_sold',
            new_name='units_sold',
        ),
    ]
