# Generated by Django 4.1.5 on 2023-04-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0006_alter_product_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='name',
            new_name='combo_name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='group_id',
        ),
    ]
