# Generated by Django 4.1.5 on 2023-05-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0009_remove_components_units_of_measurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stocks', models.IntegerField()),
                ('product_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lumpiasys.product')),
            ],
            options={
                'db_table': 'Inventory_records',
            },
        ),
    ]
