# Generated by Django 4.0.4 on 2023-05-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0010_inventoryrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='quantity_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='units_sold',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryrecords',
            name='stocks',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_level',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_order',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
