# Generated by Django 4.1.5 on 2023-05-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumpiasys', '0010_inventoryrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
        migrations.AlterModelTable(
            name='account',
            table='Accounts',
        ),
    ]
